# Gradient Descent - Boston Dataset

#### If there is problem then it is only in data_conv()

In [1]:
import numpy as np

In [2]:
def data_conv():
    data_train1 = np.genfromtxt("Datasets/project_training_boston_x_y_train.csv",delimiter=',')
    y_train = data_train1[:,-1]
    x_train = data_train1[:,:-1]
    #x_train[:,-1] = 1    //Don't do this kind of thing because it do shallow copy
    M = len(x_train)
    new_col = np.ones((M,1))
    x_train = np.append(x_train,new_col,axis = 1)
    
    x_test = np.genfromtxt("Datasets/project_test_boston_x_test.csv",delimiter=',')
    # x_test does not have Y column in it so we have to add column containing 1 explicitly
    x_test = np.array(x_test)
    M = len(x_test)
    new_col = np.ones((M,1))
    x_test = np.append(x_test,new_col,axis = 1)
    return x_train, y_train, x_test

In [3]:
def step_gradient(m,X_train,Y_train,learning_rate):
    N = len(X_train[0])
    M = len(X_train)
    m_slope=np.zeros(N)
    for i in range(M):
        X = X_train[i]
        Y = Y_train[i]
        for j in range(N):
            m_slope[j] += (-2/M)* (Y - (m*X).sum()) * (X[j])
    new_m = m - learning_rate * m_slope
    return new_m

In [4]:
def cost(m, x, y):
    cost=0
    for i in range(len(x)):
        cost+=(1/len(x))*((y[i]-sum(m*x[i]))**2)
    print(cost)

In [47]:
def gd(X_train, Y_train, learning_rate, num_iteration):
    M = len(X_train)
    N = len(X_train[0])
    m = np.zeros(N)
    for i in range(num_iteration):
        m = step_gradient(m,X_train,Y_train,learning_rate)
        print("itr= ", i, "cost=", end=' ')
        cost(m, X_train, Y_train)
    return m

In [6]:
# Main code
X_train , Y_train, X_test = data_conv()
learning_rate = 0.1
num_iteration = 300
m = gd(X_train, Y_train, learning_rate, num_iteration)
Y_predict = (m*X_test).sum(axis = 1)
Y_predict = Y_predict.reshape(-1,1)
Y_predict

itr=  0 cost= 374.24035597919686
itr=  1 cost= 245.37909656079904
itr=  2 cost= 165.10614192173668
itr=  3 cost= 114.49508621191686
itr=  4 cost= 82.43432664281796
itr=  5 cost= 62.041704688310936
itr=  6 cost= 49.0154746660482
itr=  7 cost= 40.65519326019772
itr=  8 cost= 35.25972835067592
itr=  9 cost= 31.754121492629718
itr=  10 cost= 29.457161634001743
itr=  11 cost= 27.936007022144533
itr=  12 cost= 26.914922412896374
itr=  13 cost= 26.217802951980175
itr=  14 cost= 25.73187282296311
itr=  15 cost= 25.38469911771804
itr=  16 cost= 25.129603525591072
itr=  17 cost= 24.936384410518777
itr=  18 cost= 24.785404792037365
itr=  19 cost= 24.66381822190748
itr=  20 cost= 24.563155143621433
itr=  21 cost= 24.477776518190062
itr=  22 cost= 24.403881200700233
itr=  23 cost= 24.338867434896194
itr=  24 cost= 24.280921148348455
itr=  25 cost= 24.228749732407813
itr=  26 cost= 24.181409300585187
itr=  27 cost= 24.13819212010117
itr=  28 cost= 24.09855285948923
itr=  29 cost= 24.06205993819115
i

itr=  242 cost= 23.466880247706865
itr=  243 cost= 23.46685829636901
itr=  244 cost= 23.46683692605903
itr=  245 cost= 23.46681612138942
itr=  246 cost= 23.466795867380597
itr=  247 cost= 23.466776149450403
itr=  248 cost= 23.466756953403117
itr=  249 cost= 23.46673826541953
itr=  250 cost= 23.466720072046787
itr=  251 cost= 23.46670236018861
itr=  252 cost= 23.466685117095903
itr=  253 cost= 23.466668330357432
itr=  254 cost= 23.466651987890927
itr=  255 cost= 23.466636077934357
itr=  256 cost= 23.466620589037273
itr=  257 cost= 23.466605510052695
itr=  258 cost= 23.466590830128965
itr=  259 cost= 23.46657653870196
itr=  260 cost= 23.46656262548747
itr=  261 cost= 23.46654908047358
itr=  262 cost= 23.466535893913736
itr=  263 cost= 23.46652305631949
itr=  264 cost= 23.466510558453756
itr=  265 cost= 23.466498391324016
itr=  266 cost= 23.466486546176025
itr=  267 cost= 23.46647501448732
itr=  268 cost= 23.466463787961235
itr=  269 cost= 23.466452858520615
itr=  270 cost= 23.46644221830

array([[12.42989444],
       [29.02039391],
       [22.37354643],
       [24.46703242],
       [20.62175438],
       [ 2.73145008],
       [30.38110212],
       [24.85603445],
       [18.66257161],
       [23.53976431],
       [24.11358439],
       [17.71638788],
       [17.46398303],
       [21.66356997],
       [42.31859907],
       [23.85979426],
       [24.47528322],
       [27.55265382],
       [20.24532477],
       [31.16515999],
       [23.80379308],
       [25.00538134],
       [33.95493979],
       [36.43002887],
       [32.04938087],
       [16.70445641],
       [23.47622056],
       [32.95854932],
       [25.16710232],
       [33.71101947],
       [16.89127364],
       [26.04023426],
       [23.2739599 ],
       [25.4751929 ],
       [15.0088932 ],
       [29.59188242],
       [26.24833369],
       [20.39050928],
       [24.42398968],
       [ 9.44836666],
       [ 8.37393997],
       [29.0090706 ],
       [29.59695559],
       [19.76416454],
       [20.36709015],
       [ 3

In [7]:
np.savetxt('Datasets/project_predict_boston_y_predict.csv', Y_predict, fmt='%.5f')

## Adding Extra Variable for better result

In [16]:
def data_conv():
    data_train1 = np.genfromtxt("Datasets/project_training_boston_x_y_train.csv",delimiter=',')
    y_train = data_train1[:,-1]
    x_train = data_train1[:,:-1]
    #x_train[:,-1] = 1    //Don't do this kind of thing because it do shallow copy
    square = []
    for i in x_train:
        square.append(i**2)
    square = np.array(square)
    x_train = np.append(x_train, square, axis = 1)
    M = len(x_train)
    new_col = np.ones((M,1))
    x_train = np.append(x_train,new_col,axis = 1)
    
    x_test = np.genfromtxt("Datasets/project_test_boston_x_test.csv",delimiter=',')
    # x_test does not have Y column in it so we have to add column containing 1 explicitly
    x_test = np.array(x_test)
    square = []
    for i in x_test:
        square.append(i**2)
    square = np.array(square)
    x_test = np.append(x_test, square, axis = 1)
    
    M = len(x_test)
    new_col = np.ones((M,1))
    x_test = np.append(x_test,new_col,axis = 1)
    return x_train, y_train, x_test

In [17]:
# Main code
X_train , Y_train, X_test = data_conv()
learning_rate = 0.01
num_iteration = 300
m = gd(X_train, Y_train, learning_rate, num_iteration)
Y_predict = (m*X_test).sum(axis = 1)
Y_predict = Y_predict.reshape(-1,1)
Y_predict

itr=  0 cost= 354.1886167574412
itr=  1 cost= 251.10756035902241
itr=  2 cost= 201.16398653549004
itr=  3 cost= 173.5004107706735
itr=  4 cost= 155.8331810826478
itr=  5 cost= 143.08861190250389
itr=  6 cost= 133.06344892135775
itr=  7 cost= 124.73207158126526
itr=  8 cost= 117.572870282275
itr=  9 cost= 111.29259633583487
itr=  10 cost= 105.70916652481424
itr=  11 cost= 100.6992800479495
itr=  12 cost= 96.1735174714571
itr=  13 cost= 92.06363966836642
itr=  14 cost= 88.31560940560239
itr=  15 cost= 84.88546870375855
itr=  16 cost= 81.73673702223817
itr=  17 cost= 78.83867297369525
itr=  18 cost= 76.1650567043792
itr=  19 cost= 73.69330366651413
itr=  20 cost= 71.40379953981311
itr=  21 cost= 69.27938882564946
itr=  22 cost= 67.3049739043146
itr=  23 cost= 65.46719573962496
itr=  24 cost= 63.75417631422528
itr=  25 cost= 62.155308598432946
itr=  26 cost= 60.66108366597273
itr=  27 cost= 59.26294719294218
itr=  28 cost= 57.95317943483744
itr=  29 cost= 56.724794126379145
itr=  30 cost= 

itr=  243 cost= 23.76275469620156
itr=  244 cost= 23.733313938233525
itr=  245 cost= 23.704071371232317
itr=  246 cost= 23.67502508086404
itr=  247 cost= 23.646173177953454
itr=  248 cost= 23.617513798046108
itr=  249 cost= 23.589045100979806
itr=  250 cost= 23.560765270465215
itr=  251 cost= 23.532672513675404
itr=  252 cost= 23.504765060844125
itr=  253 cost= 23.477041164872443
itr=  254 cost= 23.449499100943832
itr=  255 cost= 23.422137166147092
itr=  256 cost= 23.394953679107488
itr=  257 cost= 23.36794697962519
itr=  258 cost= 23.341115428321537
itr=  259 cost= 23.314457406292448
itr=  260 cost= 23.28797131476913
itr=  261 cost= 23.261655574785543
itr=  262 cost= 23.235508626852983
itr=  263 cost= 23.209528930640985
itr=  264 cost= 23.183714964665008
itr=  265 cost= 23.158065225980366
itr=  266 cost= 23.132578229882267
itr=  267 cost= 23.10725250961197
itr=  268 cost= 23.08208661606907
itr=  269 cost= 23.05707911752895
itr=  270 cost= 23.03222859936669
itr=  271 cost= 23.007533663

array([[10.69943715],
       [28.82708616],
       [24.74053206],
       [25.50523819],
       [17.59133715],
       [13.57934645],
       [24.00442175],
       [26.02752116],
       [18.8374602 ],
       [22.31757217],
       [24.58030219],
       [18.18074455],
       [20.42824013],
       [15.97300307],
       [47.75479325],
       [23.84922915],
       [27.11757076],
       [27.77264897],
       [20.13874991],
       [33.97114407],
       [15.78203806],
       [20.25684983],
       [31.25653461],
       [33.74298699],
       [33.226259  ],
       [16.83559709],
       [22.3131225 ],
       [28.47650221],
       [22.26833836],
       [29.65691123],
       [16.72113785],
       [25.74722672],
       [24.75714756],
       [26.26086988],
       [12.12399022],
       [27.01247885],
       [24.65629559],
       [18.44465869],
       [22.60214833],
       [10.52377294],
       [17.05862317],
       [23.14219457],
       [28.83746963],
       [18.67333906],
       [16.9019016 ],
       [11

## Using Feature Scaling

In [35]:
from sklearn import preprocessing

In [36]:
def data_conv():
    data_train1 = np.genfromtxt("Datasets/project_training_boston_x_y_train.csv",delimiter=',')
    scaler = preprocessing.StandardScaler()
    y_train = data_train1[:,-1]
    x_train = data_train1[:,:-1]
    #x_train[:,-1] = 1    //Don't do this kind of thing because it do shallow copy
    square = []
    for i in x_train:
        square.append(i**2)
    square = np.array(square)
    x_train = np.append(x_train, square, axis = 1)
    M = len(x_train)
    new_col = np.ones((M,1))
    x_train = np.append(x_train,new_col,axis = 1)
    
    x_test = np.genfromtxt("Datasets/project_test_boston_x_test.csv",delimiter=',')
    # x_test does not have Y column in it so we have to add column containing 1 explicitly
    x_test = np.array(x_test)
    square = []
    for i in x_test:
        square.append(i**2)
    square = np.array(square)
    x_test = np.append(x_test, square, axis = 1)
    
    M = len(x_test)
    new_col = np.ones((M,1))
    x_test = np.append(x_test,new_col,axis = 1)
    
    
    scaler.fit(x_train)
    x_train = scaler.transform(x_train)
    x_test = scaler.transform(x_test)
    return x_train, y_train, x_test

In [46]:
# Main code
X_train , Y_train, X_test = data_conv()
learning_rate = 0.11
num_iteration = 300
m = gd(X_train, Y_train, learning_rate, num_iteration)
Y_predict = (m*X_test).sum(axis = 1)
Y_predict = Y_predict.reshape(-1,1)
Y_predict

itr=  0 cost= 564.4025633336391
itr=  1 cost= 549.0453358620306
itr=  2 cost= 541.3412400012505
itr=  3 cost= 537.1631201340526
itr=  4 cost= 534.76195443594
itr=  5 cost= 533.3092554708217
itr=  6 cost= 532.3845253025135
itr=  7 cost= 531.7639645410837
itr=  8 cost= 531.3241408249789
itr=  9 cost= 530.995030983844
itr=  10 cost= 530.7359783574506
itr=  11 cost= 530.5228971566437
itr=  12 cost= 530.3412469106494
itr=  13 cost= 530.182077459283
itr=  14 cost= 530.0397581099497
itr=  15 cost= 529.9106534793256
itr=  16 cost= 529.7923419174448
itr=  17 cost= 529.6831496445103
itr=  18 cost= 529.5818707465874
itr=  19 cost= 529.487597579227
itr=  20 cost= 529.3996172297951
itr=  21 cost= 529.3173477395518
itr=  22 cost= 529.2402983838459
itr=  23 cost= 529.168044585419
itr=  24 cost= 529.1002117783046
itr=  25 cost= 529.0364647829367
itr=  26 cost= 528.9765006030382
itr=  27 cost= 528.9200433700781
itr=  28 cost= 528.8668406548597
itr=  29 cost= 528.8166606656822
itr=  30 cost= 528.7692900

itr=  249 cost= 527.3661231224165
itr=  250 cost= 527.3653566556922
itr=  251 cost= 527.3645997140906
itr=  252 cost= 527.3638521761616
itr=  253 cost= 527.3631139220537
itr=  254 cost= 527.3623848335043
itr=  255 cost= 527.3616647938094
itr=  256 cost= 527.3609536878042
itr=  257 cost= 527.3602514018401
itr=  258 cost= 527.359557823769
itr=  259 cost= 527.3588728429161
itr=  260 cost= 527.3581963500624
itr=  261 cost= 527.3575282374265
itr=  262 cost= 527.3568683986413
itr=  263 cost= 527.3562167287357
itr=  264 cost= 527.3555731241177
itr=  265 cost= 527.3549374825496
itr=  266 cost= 527.3543097031392
itr=  267 cost= 527.353689686309
itr=  268 cost= 527.3530773337897
itr=  269 cost= 527.3524725485944
itr=  270 cost= 527.3518752350043
itr=  271 cost= 527.3512852985511
itr=  272 cost= 527.3507026460007
itr=  273 cost= 527.350127185333
itr=  274 cost= 527.3495588257304
itr=  275 cost= 527.3489974775574
itr=  276 cost= 527.3484430523463
itr=  277 cost= 527.3478954627794
itr=  278 cost= 5

array([[ -9.32700934],
       [  6.06871702],
       [ -0.27465265],
       [  1.2672236 ],
       [ -2.89962492],
       [ -8.64251029],
       [  5.48030795],
       [  0.6547919 ],
       [ -3.94685991],
       [  0.78096228],
       [  1.9927142 ],
       [ -5.88175022],
       [ -4.37295481],
       [ -3.57053358],
       [ 26.15424263],
       [ -0.30103158],
       [  2.37626954],
       [  3.61788853],
       [ -4.98377187],
       [  8.75569929],
       [ -1.49638603],
       [  1.40644685],
       [ 12.93241486],
       [ 12.96851591],
       [ 10.75965392],
       [ -5.0773903 ],
       [  0.42303131],
       [  9.36069122],
       [  0.31546621],
       [  9.99547105],
       [ -6.9032978 ],
       [  3.54736709],
       [ -0.14255721],
       [  0.81040234],
       [-10.36392119],
       [  5.95644806],
       [  2.49904039],
       [ -2.97246211],
       [  0.0651857 ],
       [-13.08556597],
       [ -6.17680211],
       [  4.07737778],
       [  7.79827032],
       [ -3

## Rough Work

In [8]:
x_test = np.genfromtxt("Datasets/project_test_boston_x_test.csv",delimiter=',')

# x_test does not have Y column in it so we have to add column containing 1 explicitly
x_test = np.array(x_test)
M = len(x_test)
new_col = np.ones((M,1))
x_test = np.append(x_test,new_col,axis = 1)

In [9]:
x_test.shape

(127, 14)

In [10]:
x_test = np.genfromtxt("Datasets/project_test_boston_x_test.csv",delimiter=',')

In [11]:
temp = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
temp

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
M =5
new_col = np.zeros((M,1))
new_col

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [13]:
summ = ans.sum(axis =1)
summ

NameError: name 'ans' is not defined

In [ ]:
ans = summ.reshape(-1,1)

In [ ]:
ans

In [ ]:
summ.reshape(-1,1)

In [ ]:
ans

In [ ]:
summ

In [ ]:
def data_conv():
    data_train1 = np.genfromtxt("Datasets/project_training_boston_x_y_train.csv",delimiter=',')
    y_train = data_train1[:,-1]
    data_train2 = np.genfromtxt("Datasets/project_training_boston_x_y_train.csv",delimiter=',')
    x_train = data_train2
    # Last row was Y we are using that as a extra column containg 1
    x_train[:,-1] = 1
    
    
    x_test = np.genfromtxt("Datasets/project_test_boston_x_test.csv",delimiter=',')
    # x_test does not have Y column in it so we have to add column containing 1 explicitly
    x_test = np.array(x_test)
    M = len(x_test)
    new_col = np.ones((M,1))
    x_test = np.append(x_test,new_col,axis = 1)
    return x_train, y_train, x_test

In [ ]:
x_train, y_train, x_test = data_conv()

In [ ]:
x_train

In [ ]:
y_train

In [ ]:
x_test

In [ ]:
data_train = np.genfromtxt("Datasets/project_training_boston_x_y_train.csv",delimiter=',')

In [ ]:
type(data_train)

In [ ]:
temp = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
temp

In [ ]:
y = temp
y[:,-1] = 0
temp

In [ ]:
abc = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
abc

In [ ]:
b  = abc
b[1][2] = 0
abc

In [ ]:
data_train2 = np.genfromtxt("Datasets/project_training_boston_x_y_train.csv",delimiter=',')
x_train = data_train2[:,-1]
x_train

In [ ]:
def data_conv():
    data_train1 = np.genfromtxt("Datasets/project_training_boston_x_y_train.csv",delimiter=',')
    y_train = data_train1[:,-1]
    x_train = data_train1
    # Last row was Y we are using that as a extra column containg 1
    x_train[:,-1] = 1
    
    
    x_test = np.genfromtxt("Datasets/project_test_boston_x_test.csv",delimiter=',')
    # x_test does not have Y column in it so we have to add column containing 1 explicitly
    x_test = np.array(x_test)
    M = len(x_test)
    new_col = np.ones((M,1))
    x_test = np.append(x_test,new_col,axis = 1)
    return x_train, y_train, x_test

In [ ]:
x_train, y_train, x_test = data_conv()

In [ ]:
y_train

In [ ]:
x_train