In [1]:
from nltk.corpus import movie_reviews

In [2]:
movie_reviews.categories()

['neg', 'pos']

In [3]:
movie_reviews.fileids()

['neg/cv000_29416.txt',
 'neg/cv001_19502.txt',
 'neg/cv002_17424.txt',
 'neg/cv003_12683.txt',
 'neg/cv004_12641.txt',
 'neg/cv005_29357.txt',
 'neg/cv006_17022.txt',
 'neg/cv007_4992.txt',
 'neg/cv008_29326.txt',
 'neg/cv009_29417.txt',
 'neg/cv010_29063.txt',
 'neg/cv011_13044.txt',
 'neg/cv012_29411.txt',
 'neg/cv013_10494.txt',
 'neg/cv014_15600.txt',
 'neg/cv015_29356.txt',
 'neg/cv016_4348.txt',
 'neg/cv017_23487.txt',
 'neg/cv018_21672.txt',
 'neg/cv019_16117.txt',
 'neg/cv020_9234.txt',
 'neg/cv021_17313.txt',
 'neg/cv022_14227.txt',
 'neg/cv023_13847.txt',
 'neg/cv024_7033.txt',
 'neg/cv025_29825.txt',
 'neg/cv026_29229.txt',
 'neg/cv027_26270.txt',
 'neg/cv028_26964.txt',
 'neg/cv029_19943.txt',
 'neg/cv030_22893.txt',
 'neg/cv031_19540.txt',
 'neg/cv032_23718.txt',
 'neg/cv033_25680.txt',
 'neg/cv034_29446.txt',
 'neg/cv035_3343.txt',
 'neg/cv036_18385.txt',
 'neg/cv037_19798.txt',
 'neg/cv038_9781.txt',
 'neg/cv039_5963.txt',
 'neg/cv040_8829.txt',
 'neg/cv041_22364.txt',


In [4]:
movie_reviews.fileids('neg')

['neg/cv000_29416.txt',
 'neg/cv001_19502.txt',
 'neg/cv002_17424.txt',
 'neg/cv003_12683.txt',
 'neg/cv004_12641.txt',
 'neg/cv005_29357.txt',
 'neg/cv006_17022.txt',
 'neg/cv007_4992.txt',
 'neg/cv008_29326.txt',
 'neg/cv009_29417.txt',
 'neg/cv010_29063.txt',
 'neg/cv011_13044.txt',
 'neg/cv012_29411.txt',
 'neg/cv013_10494.txt',
 'neg/cv014_15600.txt',
 'neg/cv015_29356.txt',
 'neg/cv016_4348.txt',
 'neg/cv017_23487.txt',
 'neg/cv018_21672.txt',
 'neg/cv019_16117.txt',
 'neg/cv020_9234.txt',
 'neg/cv021_17313.txt',
 'neg/cv022_14227.txt',
 'neg/cv023_13847.txt',
 'neg/cv024_7033.txt',
 'neg/cv025_29825.txt',
 'neg/cv026_29229.txt',
 'neg/cv027_26270.txt',
 'neg/cv028_26964.txt',
 'neg/cv029_19943.txt',
 'neg/cv030_22893.txt',
 'neg/cv031_19540.txt',
 'neg/cv032_23718.txt',
 'neg/cv033_25680.txt',
 'neg/cv034_29446.txt',
 'neg/cv035_3343.txt',
 'neg/cv036_18385.txt',
 'neg/cv037_19798.txt',
 'neg/cv038_9781.txt',
 'neg/cv039_5963.txt',
 'neg/cv040_8829.txt',
 'neg/cv041_22364.txt',


In [5]:
print("Total : ", len(movie_reviews.fileids()))
print("Positive : ", len(movie_reviews.fileids('pos')))
print("Negative : ", len(movie_reviews.fileids('neg')))

Total :  2000
Positive :  1000
Negative :  1000


In [6]:
movie_reviews.words(movie_reviews.fileids()[5])

['capsule', ':', 'in', '2176', 'on', 'the', 'planet', ...]

## Data Cleaning

In [7]:
documents = []
for category in movie_reviews.categories():
    for fileid in movie_reviews.fileids(category):
        documents.append((movie_reviews.words(fileid), category))
        
documents[0:5]

[(['plot', ':', 'two', 'teen', 'couples', 'go', 'to', ...], 'neg'),
 (['the', 'happy', 'bastard', "'", 's', 'quick', 'movie', ...], 'neg'),
 (['it', 'is', 'movies', 'like', 'these', 'that', 'make', ...], 'neg'),
 (['"', 'quest', 'for', 'camelot', '"', 'is', 'warner', ...], 'neg'),
 (['synopsis', ':', 'a', 'mentally', 'unstable', 'man', ...], 'neg')]

In [8]:
import random
random.shuffle(documents)
documents[0:5]

[(['i', 'have', 'never', 'been', 'a', '"', 'star', ...], 'neg'),
 (['susan', 'granger', "'", 's', 'review', 'of', '"', ...], 'neg'),
 (['synopsis', ':', 'wealthy', 'cuban', 'landowner', ...], 'neg'),
 (['the', 'general', "'", 's', 'daughter', 'will', ...], 'neg'),
 (['at', 'first', 'glance', ',', 'three', 'kings', ...], 'pos')]

Now we have all the words. Now i want to clean my all the files. Now we will remove stopwords and we will do lemmitization.

In [9]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [10]:
from nltk.corpus import stopwords
import string
stops = set(stopwords.words('english'))
punctuations = list(string.punctuation)
stops.update(punctuations)

In [14]:
from nltk.corpus import wordnet
def get_simple_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [15]:
from nltk import pos_tag
def clean_review(words):
    output_words = []
    for w in words:
        if w.lower() not in stops:
            pos = pos_tag([w])
            clean_word = lemmatizer.lemmatize(w, pos = get_simple_pos(pos[0][1]))
            output_words.append(clean_word.lower())
    return output_words

In [16]:
documents = [(clean_review(doc),category) for doc, category in documents]

In [17]:
documents[0]

(['never',
  'star',
  'trek',
  'fan',
  'tell',
  'truth',
  'five',
  'film',
  'series',
  'see',
  '1',
  '2',
  '3',
  '8',
  '9',
  'disliked',
  'however',
  'always',
  'go',
  'one',
  'open',
  'mind',
  'ninth',
  'film',
  'series',
  'star',
  'trek',
  'insurrection',
  'exception',
  'drop',
  'almost',
  'completely',
  'hard',
  'core',
  'sci',
  'fi',
  'element',
  'previous',
  'one',
  'series',
  'first',
  'contact',
  'insurrection',
  'tell',
  'story',
  'planet',
  'hold',
  '600',
  'people',
  'know',
  'ba',
  'ku',
  'well',
  'fountain',
  'youth',
  'start',
  'picture',
  'villager',
  'go',
  'attack',
  'second',
  'alien',
  'specie',
  'know',
  'son',
  'want',
  'push',
  'ba',
  'ku',
  'race',
  'die',
  'also',
  'attack',
  'ba',
  'ku',
  'data',
  'brent',
  'spiner',
  'robot',
  'star',
  'trek',
  'enterprise',
  'return',
  'jean',
  'luc',
  'picard',
  'patrick',
  'stewart',
  'gang',
  'space',
  'ship',
  'one',
  'understand',
 

## Building Features

In [18]:
training_documents = documents[0:1500]
testing_documents = documents[1500:]
# We have alread randomly shuffeled the documents thats why we can do this

In [19]:
#Rough explaination
a= [1,2]
b = [5,8]
a += b
a

[1, 2, 5, 8]

In [20]:
all_words = []
for doc in training_documents:
    all_words += doc[0]

In [21]:
import nltk

In [22]:
freq = nltk.FreqDist(all_words)
freq.most_common(15)

[('film', 8402),
 ('movie', 5150),
 ('one', 4541),
 ('make', 3189),
 ('like', 2926),
 ('character', 2824),
 ('get', 2693),
 ('see', 2308),
 ('time', 2274),
 ('go', 2268),
 ('well', 2083),
 ('scene', 1974),
 ('even', 1896),
 ('good', 1792),
 ('story', 1691)]

In [23]:
common = freq.most_common(3000)
features = [i[0] for i in common]
features

['film',
 'movie',
 'one',
 'make',
 'like',
 'character',
 'get',
 'see',
 'time',
 'go',
 'well',
 'scene',
 'even',
 'good',
 'story',
 'take',
 'would',
 'much',
 'also',
 'life',
 'come',
 'look',
 'give',
 'bad',
 'two',
 'first',
 '--',
 'end',
 'know',
 'way',
 'seem',
 'work',
 'year',
 'thing',
 'plot',
 'say',
 'really',
 'play',
 'little',
 'show',
 'people',
 'could',
 'love',
 'man',
 'star',
 'never',
 'director',
 'new',
 'try',
 'great',
 'best',
 'performance',
 'many',
 'actor',
 'find',
 'big',
 'action',
 'want',
 'u',
 'watch',
 'role',
 'think',
 'another',
 'audience',
 'back',
 'act',
 'world',
 'still',
 'turn',
 'old',
 'something',
 'day',
 'set',
 'however',
 'though',
 'use',
 'guy',
 'every',
 'comedy',
 'feel',
 'cast',
 'real',
 'begin',
 'enough',
 'last',
 'write',
 'part',
 'around',
 'interest',
 'script',
 'run',
 'young',
 'point',
 'fact',
 'almost',
 'woman',
 'long',
 'name',
 'may',
 'funny',
 'minute',
 'nothing',
 'effect',
 'right',
 'actua

In [24]:
def get_feature_dict(words):
    current_features = {}
    words_set = set(words)
    for w in features:
        current_features[w] = w in words_set
    return current_features

In [25]:
# Testing get_feature_dict function
get_feature_dict(training_documents[0][0])
# training_documents[0][0] #It contains words of document

{'film': True,
 'movie': True,
 'one': True,
 'make': True,
 'like': True,
 'character': True,
 'get': True,
 'see': True,
 'time': True,
 'go': True,
 'well': True,
 'scene': False,
 'even': False,
 'good': True,
 'story': True,
 'take': True,
 'would': False,
 'much': False,
 'also': True,
 'life': False,
 'come': True,
 'look': True,
 'give': False,
 'bad': True,
 'two': True,
 'first': True,
 '--': False,
 'end': False,
 'know': True,
 'way': True,
 'seem': True,
 'work': False,
 'year': True,
 'thing': False,
 'plot': True,
 'say': False,
 'really': False,
 'play': True,
 'little': False,
 'show': True,
 'people': True,
 'could': True,
 'love': True,
 'man': False,
 'star': True,
 'never': True,
 'director': False,
 'new': False,
 'try': True,
 'great': False,
 'best': False,
 'performance': False,
 'many': False,
 'actor': False,
 'find': False,
 'big': True,
 'action': True,
 'want': True,
 'u': False,
 'watch': False,
 'role': True,
 'think': False,
 'another': True,
 'audience

In [26]:
training_data = [(get_feature_dict(doc), category) for doc, category in training_documents]
testing_data = [(get_feature_dict(doc), category) for doc, category in testing_documents]

In [27]:
training_data[0]

({'film': True,
  'movie': True,
  'one': True,
  'make': True,
  'like': True,
  'character': True,
  'get': True,
  'see': True,
  'time': True,
  'go': True,
  'well': True,
  'scene': False,
  'even': False,
  'good': True,
  'story': True,
  'take': True,
  'would': False,
  'much': False,
  'also': True,
  'life': False,
  'come': True,
  'look': True,
  'give': False,
  'bad': True,
  'two': True,
  'first': True,
  '--': False,
  'end': False,
  'know': True,
  'way': True,
  'seem': True,
  'work': False,
  'year': True,
  'thing': False,
  'plot': True,
  'say': False,
  'really': False,
  'play': True,
  'little': False,
  'show': True,
  'people': True,
  'could': True,
  'love': True,
  'man': False,
  'star': True,
  'never': True,
  'director': False,
  'new': False,
  'try': True,
  'great': False,
  'best': False,
  'performance': False,
  'many': False,
  'actor': False,
  'find': False,
  'big': True,
  'action': True,
  'want': True,
  'u': False,
  'watch': False,


## Classification Using NLTK Naive Bayes

In [28]:
from nltk import NaiveBayesClassifier

In [29]:
classifier = NaiveBayesClassifier.train(training_data)

In [30]:
nltk.classify.accuracy(classifier, testing_data)

0.77

In [31]:
classifier.show_most_informative_features(15)

Most Informative Features
             outstanding = True              pos : neg    =     15.9 : 1.0
                 refresh = True              pos : neg    =     11.8 : 1.0
                  spacey = True              pos : neg    =     10.0 : 1.0
                   jolie = True              neg : pos    =      9.3 : 1.0
               ludicrous = True              neg : pos    =      8.7 : 1.0
                   anger = True              pos : neg    =      8.2 : 1.0
                lifeless = True              neg : pos    =      7.3 : 1.0
             wonderfully = True              pos : neg    =      7.0 : 1.0
                  sloppy = True              neg : pos    =      6.8 : 1.0
                  welles = True              neg : pos    =      6.8 : 1.0
                    lame = True              neg : pos    =      6.3 : 1.0
            breathtaking = True              pos : neg    =      6.1 : 1.0
                   damon = True              pos : neg    =      5.9 : 1.0

## Using Sklearn Classifiers within NLTK

In [33]:
from sklearn.svm import SVC
# using SVM for now
from nltk.classify.scikitlearn import SklearnClassifier

In [34]:
svc = SVC()
classifier_sklearn = SklearnClassifier(svc)

In [35]:
classifier_sklearn.train(training_data)

<SklearnClassifier(SVC())>

In [37]:
nltk.classify.accuracy(classifier_sklearn, testing_data)

0.846

In [38]:
from sklearn.ensemble import RandomForestClassifier
# Trying Random Forest Now

In [39]:
rfc = RandomForestClassifier()
classifier_sklearn1 = SklearnClassifier(rfc)

In [40]:
classifier_sklearn1.train(training_data)

<SklearnClassifier(RandomForestClassifier())>

In [41]:
nltk.classify.accuracy(classifier_sklearn1, testing_data)

0.776

## Count Vectorizer

Trying on dummy data

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

In [43]:
train_set = {"the sky is blue", "the sun is bright"}
count_vec = CountVectorizer(max_features = 3)
a = count_vec.fit_transform(train_set)

In [44]:
a.todense()

matrix([[0, 1, 1],
        [1, 1, 1]], dtype=int64)

In [45]:
count_vec.get_feature_names()

['blue', 'is', 'the']

In [46]:
train_set = {"the sky sky is blue", "the sun is bright"}
count_vec = CountVectorizer(max_features = 3)
a = count_vec.fit_transform(train_set)
a.todense()

matrix([[1, 2, 1],
        [1, 0, 1]], dtype=int64)

In [47]:
count_vec.get_feature_names()

['is', 'sky', 'the']

### Using On Cleaned Movie Data

Part before creating features is done by now

In [49]:
categories = [category for document, category in documents]

In [50]:
# Rough work
a = ["Avi", "nash"]
" ".join(a)

'Avi nash'

In [51]:
text_documents = [" ".join(document) for document, category in documents]

In [52]:
text_documents[0]

'never star trek fan tell truth five film series see 1 2 3 8 9 disliked however always go one open mind ninth film series star trek insurrection exception drop almost completely hard core sci fi element previous one series first contact insurrection tell story planet hold 600 people know ba ku well fountain youth start picture villager go attack second alien specie know son want push ba ku race die also attack ba ku data brent spiner robot star trek enterprise return jean luc picard patrick stewart gang space ship one understand data somehow take another force several star trek member travel planet ba ku picard meet start fall love one inhabitant sultry kind alien woman donna murphy six hundred year old look thirty star trek insurrection completely unoriginal cheap look installment series big step 1996 first contact least appear try make something bit different insurrection however play like low rent episode television show due small scale generic storyline emphasis one liner rather ex

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
x_train,x_test, y_train, y_test = train_test_split(text_documents, categories)

In [58]:
count_vec = CountVectorizer(max_features = 2000)
x_train_features = count_vec.fit_transform(x_train)
x_train_features.todense()

matrix([[3, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [59]:
count_vec.get_feature_names()

['000',
 '10',
 '100',
 '12',
 '13',
 '15',
 '17',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '20',
 '30',
 '50',
 '60',
 '70',
 '80',
 '90',
 'abandon',
 'ability',
 'able',
 'absolutely',
 'absurd',
 'academy',
 'accent',
 'accept',
 'accident',
 'accompany',
 'accomplish',
 'achieve',
 'achievement',
 'across',
 'act',
 'action',
 'actor',
 'actress',
 'actual',
 'actually',
 'ad',
 'adam',
 'adapt',
 'adaptation',
 'add',
 'addition',
 'admit',
 'adult',
 'adventure',
 'affair',
 'affleck',
 'afraid',
 'african',
 'age',
 'agent',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aim',
 'air',
 'al',
 'ala',
 'alan',
 'alex',
 'alice',
 'alien',
 'alive',
 'allen',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'amaze',
 'america',
 'american',
 'among',
 'amount',
 'amuse',
 'amy',
 'anderson',
 'andrew',
 'angel',
 'angle',
 'angry',
 'animal',
 'animate',
 'animation',
 'anna',
 'annie',
 'annoy',
 'another',
 'answer',
 'anth

In [61]:
x_test_features = count_vec.transform(x_test)
x_test_features

<500x2000 sparse matrix of type '<class 'numpy.int64'>'
	with 83350 stored elements in Compressed Sparse Row format>

In [62]:
from sklearn.svm import SVC

In [63]:
svc = SVC()
svc.fit(x_train_features,y_train)

SVC()

In [64]:
svc.score(x_test_features, y_test)

0.79

## Using n-gram

In [65]:
count_vec = CountVectorizer(max_features = 2000, ngram_range = (2,3))
x_train_features = count_vec.fit_transform(x_train)
x_train_features.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [66]:
count_vec.get_feature_names()

['10 10',
 '10 minute',
 '10 scale',
 '10 thing',
 '10 thing hate',
 '10 year',
 '100 million',
 '100 minute',
 '14 year',
 '15 minute',
 '19th century',
 '20 minute',
 '20 year',
 '2001 space',
 '2001 space odyssey',
 '20th century',
 '30 minute',
 '30 year',
 '90 minute',
 'able make',
 'absolutely nothing',
 'academy award',
 'across country',
 'act ability',
 'act film',
 'act like',
 'act talent',
 'action adventure',
 'action comedy',
 'action film',
 'action flick',
 'action hero',
 'action movie',
 'action scene',
 'action sequence',
 'action thriller',
 'actor film',
 'actor play',
 'actually get',
 'adam sandler',
 'adult film',
 'african american',
 'air force',
 'al pacino',
 'albert brook',
 'ali larter',
 'alicia silverstone',
 'almost always',
 'almost completely',
 'almost entirely',
 'almost every',
 'along line',
 'along way',
 'already know',
 'also direct',
 'also funny',
 'also get',
 'also give',
 'also good',
 'also happens',
 'also help',
 'also include',
 'also

In [67]:
x_test_features = count_vec.transform(x_test)
x_test_features

<500x2000 sparse matrix of type '<class 'numpy.int64'>'
	with 12269 stored elements in Compressed Sparse Row format>

In [68]:
svc = SVC()
svc.fit(x_train_features,y_train)
svc.score(x_test_features, y_test)

0.706

## Using max_df and min_df 

In [69]:
count_vec = CountVectorizer(max_features = 2000, max_df = 0.8, min_df = 0.1)
x_train_features = count_vec.fit_transform(x_train)
x_train_features.todense()

matrix([[1, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 1, 3, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 1, 0, 1],
        [1, 0, 2, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0]], dtype=int64)

In [70]:
count_vec.get_feature_names()

['10',
 'able',
 'act',
 'action',
 'actor',
 'actually',
 'add',
 'age',
 'almost',
 'along',
 'already',
 'also',
 'although',
 'always',
 'american',
 'another',
 'anyone',
 'anything',
 'appear',
 'around',
 'ask',
 'attempt',
 'attention',
 'audience',
 'away',
 'back',
 'bad',
 'base',
 'beautiful',
 'become',
 'becomes',
 'begin',
 'behind',
 'believe',
 'best',
 'big',
 'bit',
 'black',
 'body',
 'book',
 'boring',
 'boy',
 'break',
 'bring',
 'brother',
 'call',
 'camera',
 'car',
 'care',
 'career',
 'carry',
 'case',
 'cast',
 'cause',
 'certainly',
 'chance',
 'change',
 'character',
 'chase',
 'child',
 'city',
 'classic',
 'close',
 'co',
 'come',
 'comedy',
 'comic',
 'complete',
 'completely',
 'consider',
 'could',
 'couple',
 'course',
 'create',
 'credit',
 'cut',
 'dark',
 'daughter',
 'david',
 'day',
 'dead',
 'deal',
 'death',
 'despite',
 'dialogue',
 'die',
 'different',
 'direct',
 'direction',
 'director',
 'do',
 'drama',
 'dream',
 'early',
 'easy',
 'effec

In [71]:
x_test_features = count_vec.transform(x_test)
x_test_features

<500x442 sparse matrix of type '<class 'numpy.int64'>'
	with 47583 stored elements in Compressed Sparse Row format>

In [72]:
svc = SVC()
svc.fit(x_train_features,y_train)
svc.score(x_test_features, y_test)

0.756