In [1]:
import numpy as np

In [2]:
#AND function inputs
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,0,0,1]]).T
x.shape , y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

### Forward Propagation without hidden layer

In [8]:
weights = 2*np.random.random((2,1)) - 1
bias = 2*np.random.random(1) - 1
weights, bias

(array([[-0.73171152],
        [ 0.91745384]]),
 array([-0.29585281]))

In [9]:
output0 = x
output = sig(np.dot(output0,weights)+ bias)
output

array([[0.42657161],
       [0.65058259],
       [0.26355658],
       [0.47250016]])

 ### Forward Propagation with hidden layer

In [10]:
wh = 2 * np.random.random((2,2)) - 1    #weight hidden
bh = 2 * np.random.random((1,2)) - 1    #bias hidden
wo = 2 * np.random.random((2,1)) - 1    #weight output
bo = 2 * np.random.random((1,1)) - 1    #bias output
#np.random.random((No. of Input, No. of Fuction in layer))

In [12]:
output0 = x
outputHidden = sig(np.dot(output0,wh)+ bh)
output = sig(np.dot(outputHidden , wo) + bo)
output

array([[0.6195206 ],
       [0.5978521 ],
       [0.64163213],
       [0.61904948]])

What we done above is just taken random values of weights and done forward propogation. We were just understanding how to do forward propogation, we haven't considered values of y yet.

In [15]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

## Implementing a simple Neural Network

In [36]:
weights = 2*np.random.random((2,1)) - 1
bias = 2*np.random.random(1) - 1
lr = 0.1 #learning rate
weights, bias

(array([[-0.25376631],
        [ 0.94719186]]),
 array([-0.68548258]))

In [34]:
for iter in range(10000):
    output0 = x
    output = sig(np.dot(output0,weights)+ bias)

    first_term = output - y
    input_for_last_layer = np.dot(output0,weights)+ bias
    second_term = derivativeSig(input_for_last_layer)  # it is same as output*(1-output)
    first_two = first_term*second_term
    first_two.shape

    changes = np.array([[0.0],[0.0]])
    # storing derivatives wrt weights

    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * output0[j][i]
    weights = weights - lr * changes

    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0] * 1
    bias = bias - lr * bias_change
    
output = sig(np.dot(x,weights)+bias)
weights, bias, output

(array([[5.46816198],
        [5.46816197]]),
 array([-8.29498527]),
 array([[2.49703834e-04],
        [5.58917893e-02],
        [5.58917897e-02],
        [9.33475144e-01]]))

### Optimizing code using Vectors Operation

In [38]:
weights = 2*np.random.random((2,1)) - 1
bias = 2*np.random.random(1) - 1
lr = 0.1 #learning rate
weights, bias

(array([[ 0.28678216],
        [-0.72417446]]),
 array([0.52777548]))

In [39]:
for iter in range(10000):
    output0 = x
    output = sig(np.dot(output0,weights)+ bias)

    first_term = output - y
    input_for_last_layer = np.dot(output0,weights)+ bias
    second_term = derivativeSig(input_for_last_layer)  # it is same as output*(1-output)
    first_two = first_term*second_term
    first_two.shape

    changes = np.dot(output0.T, first_two)
    
    weights = weights - lr * changes

    bias_change = np.sum(first_two)
    bias = bias - lr * bias_change
    
output = sig(np.dot(x,weights)+bias)
weights, bias, output

(array([[5.47183128],
        [5.47183127]]),
 array([-8.30047284]),
 array([[2.48337659e-04],
        [5.57959205e-02],
        [5.57959212e-02],
        [9.33589999e-01]]))

# NeuralNetwork - One Hidden Layer

In [1]:
import numpy as np

In [2]:
# Implementing XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,1,1,0]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [12]:
# one hidden layer weights
wh = 2 * np.random.random((2,2)) - 1    
bh = 2 * np.random.random((1,2)) - 1   
wo = 2 * np.random.random((2,1)) - 1    
bo = 2 * np.random.random((1,1)) - 1    
lr = 0.5

In [ ]:
# for iter in range(10000):
#     output0 = x
#     output = sig(np.dot(output0,weights)+ bias)

#     first_term = output - y
#     input_for_last_layer = np.dot(output0,weights)+ bias
#     second_term = derivativeSig(input_for_last_layer)  # it is same as output*(1-output)
#     first_two = first_term*second_term
#     first_two.shape

#     changes = np.dot(output0.T, first_two)
    
#     weights = weights - lr * changes

#     bias_change = np.sum(first_two)
#     bias = bias - lr * bias_change
    
# output = sig(np.dot(x,weights)+bias)
# weights, bias, output

In [13]:
# forward propogation with one hidden layer
for iter in range(10000):
    output0 = X
    inputHidden = np.dot(output0,wh)+ bh
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden , wo) + bo
    output = sig(inputForOutputLayer)


    first_term_output_layer = output-Y
    second_term_output_layer = derivativeSig(inputForOutputLayer)
    first_two_output_layer = first_term_output_layer*second_term_output_layer

    first_term_hidden_layer = np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer*second_term_hidden_layer

    # You can compare with the code of w/o output layer to understand
    changes_output = np.dot(outputHidden.T, first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer, axis=0, keepdims=True) #It is exactly same, Just for vector dot product we are using keepdims

    changes_hidden = np.dot(output0.T, first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, axis=0, keepdims=True)

    wo = wo - lr*changes_output
    bo = bo - lr*changes_output_bias

    wh = wh - lr*changes_hidden
    bh = bh - lr*changes_hidden_bias
    
    
output0 = X
inputHidden = np.dot(output0,wh)+ bh
outputHidden = sig(inputHidden)
inputForOutputLayer = np.dot(outputHidden , wo) + bo
output = sig(inputForOutputLayer)
output, wh, bh, wo, bo

(array([[0.02259906],
        [0.97664597],
        [0.97664566],
        [0.02846948]]),
 array([[-5.19446305, -5.56186702],
        [-5.19463272, -5.56223181]]),
 array([[7.76104882, 2.21747942]]),
 array([[ 8.80177776],
        [-9.36274747]]),
 array([[-4.12161586]]))