In [2]:
import tensorflow as tf
print(tf.__version__)

2.3.0


### Constants

In [3]:
a = tf.constant(6)
b = tf.constant(9)
a, b

(<tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

In [4]:
c = a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [5]:
tf.print(c)

15


In [6]:
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x

# Build a graph.
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b

# Launch the graph in a session.
sess = tf.compat.v1.Session()

# Evaluate the tensor `c`.
print(sess.run(c)) # prints 30.0

30.0


In [7]:
a1 = tf.constant([[3,3]])
a2 = tf.constant([[3],[3]])
tf.matmul(a1,a2)

<tf.Tensor 'MatMul:0' shape=(1, 1) dtype=int32>

In [8]:
res = tf.matmul(a1,a2)
sess.run(res)

array([[18]])

### Sessions

In [9]:
sess.close()
#Closes session

In [11]:
sess.run(c)
# Can't use session for closed session

RuntimeError: Attempted to use a closed Session.

In [12]:
# Using the context manager.
with tf.compat.v1.Session() as sess:
    print(sess.run(c))
    print(c.eval())
    #both are same

30.0
30.0


## Variables

In [13]:
var1 = tf.Variable(100)
var1

<tf.Variable 'Variable:0' shape=() dtype=int32>

In [14]:
var2 = tf.Variable([100])
var2

<tf.Variable 'Variable_1:0' shape=(1,) dtype=int32>

In [15]:
var3 = tf.Variable([[100]])
var3

<tf.Variable 'Variable_2:0' shape=(1, 1) dtype=int32>

In [22]:
tf.compat.v1.disable_eager_execution()
var1 = tf.Variable(100)
var2 = tf.Variable(3)
summ = tf.add(var1, var2)
sess = tf.compat.v1.Session()
sess.run(summ)
# In case of variable we have to initialize them explicitly
# Thats why this is giving error

FailedPreconditionError: Error while reading resource variable Variable_10 from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/Variable_10)
	 [[node Add_3/ReadVariableOp_1 (defined at <ipython-input-22-d22bf5d4e2c0>:4) ]]

Errors may have originated from an input operation.
Input Source operations connected to node Add_3/ReadVariableOp_1:
 Variable_10 (defined at <ipython-input-22-d22bf5d4e2c0>:3)

Original stack trace for 'Add_3/ReadVariableOp_1':
  File "C:\Users\DELL\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DELL\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\DELL\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\DELL\anaconda3\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "C:\Users\DELL\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
    self.io_loop.start()
  File "C:\Users\DELL\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\DELL\anaconda3\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\DELL\anaconda3\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\DELL\anaconda3\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\DELL\anaconda3\lib\site-packages\tornado\ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\DELL\anaconda3\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "C:\Users\DELL\anaconda3\lib\site-packages\tornado\gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "C:\Users\DELL\anaconda3\lib\site-packages\tornado\gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "C:\Users\DELL\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\DELL\anaconda3\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "C:\Users\DELL\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\DELL\anaconda3\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "C:\Users\DELL\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 543, in execute_request
    self.do_execute(
  File "C:\Users\DELL\anaconda3\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "C:\Users\DELL\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 306, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\DELL\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\DELL\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2894, in run_cell
    result = self._run_cell(
  File "C:\Users\DELL\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2940, in _run_cell
    return runner(coro)
  File "C:\Users\DELL\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\DELL\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3165, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\DELL\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3357, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\DELL\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-d22bf5d4e2c0>", line 4, in <module>
    summ = tf.add(var1, var2)
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 355, in add
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 465, in _apply_op_helper
    values = ops.convert_to_tensor(
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1909, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1326, in _dense_var_to_tensor
    return self.value()
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 555, in value
    return self._read_variable_op()
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 657, in _read_variable_op
    result = read_and_set_handle()
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 647, in read_and_set_handle
    result = gen_resource_variable_ops.read_variable_op(self._handle,
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\ops\gen_resource_variable_ops.py", line 489, in read_variable_op
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()


In [24]:
tf.compat.v1.disable_eager_execution()
var1 = tf.Variable(100)
var2 = tf.Variable(3)
summ = tf.add(var1, var2)
sess = tf.compat.v1.Session()
init = tf.compat.v1.global_variables_initializer()
sess.run(init)
sess.run(summ)

103

In [27]:
var1.assign(1269)
sess.run(var1)

100

In [29]:
sess.run(var1.assign(1269))
print(sess.run(var1))
print(sess.run(summ))

1269
1272


In [30]:
var2 = tf.Variable(3)
init = tf.compat.v1.global_variables_initializer()
sess.run(init)
assign = var2.assign(96.23)  #Will give error
sess.run(assign)
sess.run(var2)

#Because we have initialized var2 with int and later assigning the value of float

TypeError: Expected int32, got 96.23 of type 'float' instead.

## Placeholder

In [37]:
x = tf.compat.v1.placeholder(tf.int32)
y = x * tf.constant(12)

In [38]:
sess.run(y, feed_dict={x:10}) 

120

In [41]:
sess.run(y, feed_dict={x:[10,12]}) 

array([120, 144])

In [39]:
for i in range(10,13):
    print(sess.run(y, feed_dict={x:i}))

120
132
144


In [42]:
x = tf.compat.v1.placeholder(tf.int32, shape=(2,3))
y = x * tf.constant(12)
sess.run(y, feed_dict={x:[[1,2,3],[4,5,6]]}) 

array([[12, 24, 36],
       [48, 60, 72]])