In [1]:
import numpy
a = [1,2,3]
b = numpy.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


#### Create Array using NumPy

In [2]:
import numpy as np
a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
a = [1,2,3,'a',4.5]
b = np.array(a)
b

array(['1', '2', '3', 'a', '4.5'], dtype='<U11')

In [4]:
import numpy as np
a = [1,2,3,4.5]
b = np.array(a, dtype=int)
b

array([1, 2, 3, 4])

In [5]:
import numpy as np
a = [1,2,3,4.5]
b = np.array(a, dtype=float)
b

array([1. , 2. , 3. , 4.5])

In [6]:
import numpy as np
a = [1,2,3,4.5]
b = np.array(a, dtype=str)
b

array(['1', '2', '3', '4.5'], dtype='<U3')

In [38]:
import numpy as np
a = [1,2,3,'a',4.5]
b = np.array(a*5)
b

array(['1', '2', '3', 'a', '4.5', '1', '2', '3', 'a', '4.5', '1', '2',
       '3', 'a', '4.5', '1', '2', '3', 'a', '4.5', '1', '2', '3', 'a',
       '4.5'], dtype='<U11')

In [8]:
b= np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [10]:
b= np.ones(5,dtype=int)
b

array([1, 1, 1, 1, 1])

In [9]:
b= np.zeros(5)
b

array([0., 0., 0., 0., 0.])

In [11]:
b= np.full(5)
b

TypeError: full() missing 1 required positional argument: 'fill_value'

In [12]:
b= np.full(5,3)
b

array([3, 3, 3, 3, 3])

In [15]:
b = np.empty(5)
b

array([1., 1., 1., 1., 1.])

In [17]:
b = np.empty(3)
b

array([1.60218491e-306, 1.69121503e-306, 1.11260348e-306])

In [18]:
b= np.ones((5,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
b= np.full((3,5),2)
b

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [21]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b = np.arange(2,20,3)
b

array([ 2,  5,  8, 11, 14, 17])

In [24]:
b = np.arange(2,20,3,dtype=float)
b

array([ 2.,  5.,  8., 11., 14., 17.])

In [26]:
b = np.linspace(2,5)
b

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [27]:
print(b[2]-b[1])
print(b[5]-b[4])

0.06122448979591866
0.06122448979591866


In [28]:
b = np.linspace(2,5,4)
b

array([2., 3., 4., 5.])

In np.linspace both start and end are inclusive unlike lists and np.arange

In [29]:
b = np.linspace(2,5,4,dtype=int)
b

array([2, 3, 4, 5])

In [33]:
b = np.linspace(2,10,5,False,dtype=int)
b

array([2, 3, 5, 6, 8])

end point not included

In [35]:
b = np.identity(5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
b = np.eye(5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
b = np.eye(5,3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
b = np.random.rand(5)
b

array([0.88980576, 0.2762677 , 0.83395731, 0.04139924, 0.71979696])

In [42]:
b = np.random.rand(3,5)
b

array([[0.64102806, 0.83300643, 0.78154849, 0.71118836, 0.65510547],
       [0.45941226, 0.8554992 , 0.19273276, 0.38138104, 0.93305698],
       [0.72580335, 0.24507601, 0.71747921, 0.35647766, 0.80068235]])

In [43]:
b = np.random.rand(5)*10
b

array([2.19819761, 6.41311378, 5.78410596, 4.5521528 , 0.14804481])

Range converted to 0-10

In [44]:
b = np.random.randint(5)
b

0

In [45]:
b = np.random.randint(2)
b

1

In [47]:
b = np.random.randint(5,10,3)
b

array([9, 7, 7])

In [57]:
b = np.random.randint(5,25,10)
b

array([22, 10, 17, 21, 21, 24,  6, 18, 13, 24])

#### Questions

In [50]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [51]:
np.random.rand()

0.42364414275662954

In [56]:
np.random.randint(10, 4)

ValueError: low >= high

Syntax for creating a random integer array ranging from 0 to 10 of size (4, 4)

In [58]:
np.random.rand(4,4)*10

array([[1.0892458 , 0.321137  , 3.22725742, 6.29807513],
       [4.53140889, 1.70624304, 0.26405532, 5.96164247],
       [3.3421643 , 3.03622004, 6.64407307, 6.5253363 ],
       [7.88331103, 4.77493745, 1.64678398, 4.29633365]])

##### Cut the Rope

Send Feedback

Problem Statement:

You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.

Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.


Output Format :

element1 

element2 

element3

.

In [59]:
import numpy as xxx
b = xxx.linspace(0,5,10)
for i in b[1:9]:
    print(round(i,2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


#### Over

#### Indexing and Slicing

In [1]:
import numpy as np

li = [1,2,3,4,5]
arr = np.array(li)
print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [9]:
print(li[2])
print(arr[2])

3
3


In [2]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [7]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)
print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


In [11]:
print(li_2d[2][3])
print(arr_2d[2][3])
print(arr_2d[2,3])

12
12
12


###### In normal Array/List

In [13]:
# Here no problem occurs
print(li_2d[1][:3])
print(arr_2d[1][:3])
print(arr_2d[1,:3])

[5, 6, 7]
[5 6 7]
[5 6 7]


In [14]:
# Now its tricky
print(li_2d[0:3][3])

IndexError: list index out of range

In [15]:
print(li_2d[0:3][2])
# Ideally ans should be [3,7,11]

[9, 10, 11, 12]


In [16]:
# Logic behind it
x= li_2d [0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


##### In NumPy array

In [20]:
# printing like normal list
print(arr_2d[0:3][2])
# printing like NumPy
print(arr_2d[0:3,2])

[ 9 10 11 12]
[ 3  7 11]


Print like NumPy array is good and understandable

In [21]:
# this is working now
print(arr_2d[0:3,3])

[ 4  8 12]


In [23]:
# We can also print part of 2d array by using numpy
# # # #
# # # #
# 10 11 #
# 14 15 #
print(arr_2d[2:4,1:3])

[[10 11]
 [14 15]]


#### Mathematical Operations - 1D


In [1]:
import numpy as np
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

In [2]:
print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 8  3 14 10 16]
[19  1 13  4  5]


In [3]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [5]:
a=a+1
a

array([10,  5, 16, 12, 18])

In [6]:
c = a+b
c

array([29,  6, 29, 16, 23])

In [7]:
d = a-b
d

array([-9,  4,  3,  8, 13])

In [8]:
e = a*b
e

array([190,   5, 208,  48,  90])

In [9]:
f = a/b
f

array([0.52631579, 5.        , 1.23076923, 3.        , 3.6       ])

In [10]:
g = a//b
g

array([0, 5, 1, 3, 3], dtype=int32)

In [11]:
h = a**b
h

array([-1981284352,           5,           0,       20736,     1889568],
      dtype=int32)

In [13]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[10  5 16 12 18]
61
12.2
5
1
18
4


In [14]:
print(a)
print(b)

[10  5 16 12 18]
[19  1 13  4  5]


In [15]:
a>b

array([False,  True,  True,  True,  True])

In [16]:
a<b

array([ True, False, False, False, False])

In [17]:
a==b

array([False, False, False, False, False])

In [22]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(b))

[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]


In [25]:
s = [1,5,3,4,8,5]
t = [1,5,3,4]
x = np.array(s)
y = np.array(t)
print(x)
print(y)

[1 5 3 4 8 5]
[1 5 3 4]


In [26]:
z = x+y
z

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [36]:
w = np.random.randint(3,20,(3,4))
w

array([[14, 16, 10,  9],
       [ 3,  7,  7,  4],
       [14, 11,  7, 15]])

In [37]:
p = np.random.randint(3,20,(3,4))
p

array([[11,  4,  4, 13],
       [ 6, 14,  3,  4],
       [18, 12,  4, 17]])

In [41]:
afs = w+p
afs

array([[25, 20, 14, 22],
       [ 9, 21, 10,  8],
       [32, 23, 11, 32]])

#### Boolean Indexing - 1D

In [5]:
import numpy as np
a = np.array(['t','a','c','w','j','o','z','l'])
b = np.random.randint(1,20,8)
print(a)
print(b)

['t' 'a' 'c' 'w' 'j' 'o' 'z' 'l']
[10 13 14  2 19 12 12 13]


In [12]:
print(b>10)

[False  True  True False  True  True  True  True]


In [7]:
bool_arr = b>10
new_arr = b[bool_arr]
print(new_arr)

[13 14 19 12 12 13]


In [8]:
new_arr_= b[b>5]
new_arr_

array([10, 13, 14, 19, 12, 12, 13])

In [9]:
new_arr_= b[(b>5) & (b<15)]
new_arr_

array([10, 13, 14, 12, 12, 13])

In [10]:
print(b)
c = b
c

[10 13 14  2 19 12 12 13]


array([10, 13, 14,  2, 19, 12, 12, 13])

In [52]:
c[:3] = 7
c

array([ 7,  7,  7,  1, 17,  8,  5, 17])

In [53]:
c[c>10] = 69
c

array([ 7,  7,  7,  1, 69,  8,  5, 69])

In [54]:
print(c[c==69])

[69 69]


In [55]:
index = np.where(c==69)
index

(array([4, 7], dtype=int64),)

In [56]:
print(a)
print(b)
ind = np.where(b==69)
print(ind)
print(a[ind])

['t' 'a' 'c' 'w' 'j' 'o' 'z' 'l']
[ 7  7  7  1 69  8  5 69]
(array([4, 7], dtype=int64),)
['j' 'l']


#### Boolean Indexing - 2D

In [1]:
import numpy as np
a = np.random.randint(1,30,(5,6))
print(a)

[[21  2  5  6 29 13]
 [28  6 29 23 23 22]
 [ 1 18 14 11  1 19]
 [27  4 16 19  5  1]
 [13 25 12 28 16 20]]


In [2]:
a>20

array([[ True, False, False, False,  True, False],
       [ True, False,  True,  True,  True,  True],
       [False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False,  True, False, False]])

In [3]:
bool_arr = a>20
bool_arr

array([[ True, False, False, False,  True, False],
       [ True, False,  True,  True,  True,  True],
       [False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False,  True, False, False]])

In [5]:
ans = a[bool_arr]
print(ans)

[21 29 28 29 23 23 22 27 25 28]


Replace a[i][j] with 100 if a[i][j] is greater than 20

In [6]:
b = a
print(b)

[[21  2  5  6 29 13]
 [28  6 29 23 23 22]
 [ 1 18 14 11  1 19]
 [27  4 16 19  5  1]
 [13 25 12 28 16 20]]


In [7]:
b[bool_arr] = 100
print(b)

[[100   2   5   6 100  13]
 [100   6 100 100 100 100]
 [  1  18  14  11   1  19]
 [100   4  16  19   5   1]
 [ 13 100  12 100  16  20]]


In [9]:
x = np.random.randint(1,10,(2,2))
print(x)
y = np.array([[True,False],[False,False],[False,True]])
print(y)

[[2 6]
 [9 4]]
[[ True False]
 [False False]
 [False  True]]


In [10]:
x[y] = 100

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [12]:
z = [True,False]
x[z]

array([[2, 6]])

Update 99 in column index 3 inplace of 100

In [14]:
print(b)

[[100   2   5   6 100  13]
 [100   6 100 100 100 100]
 [  1  18  14  11   1  19]
 [100   4  16  19   5   1]
 [ 13 100  12 100  16  20]]


In [15]:
bool_arr = b[:,3] == 100
print(bool_arr)

[False  True False False  True]


In [16]:
b[bool_arr,3] = 99

In [17]:
b

array([[100,   2,   5,   6, 100,  13],
       [100,   6, 100,  99, 100, 100],
       [  1,  18,  14,  11,   1,  19],
       [100,   4,  16,  19,   5,   1],
       [ 13, 100,  12,  99,  16,  20]])

Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:
 [[21 20 19 18 17]
  [16 15 14 13 12]
  [11 10  9  8  7]
  [ 6  5  4  3  2]]
Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1.
Output Format :
[[ 6  5  4  3  2]
[11 10  9  8  7]
[16 15 14 13 12]
[21 20 19 18 17]]


In [18]:
import numpy as np
li =  [[21, 20, 19, 18, 17],[16, 15, 14, 13, 12],[11, 10,  9,  8,  7],[ 6 , 5 , 4 , 3,  2]]
n = np.array(li)
n = n[n[:, 1].argsort()]
print(n)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


#### NumPy Broadcasting


In [20]:
a = np.random.randint(0,10,(2,3))
b = np.random.randint(0,10,(2,2))
print(a)
print(b)

[[6 1 5]
 [2 3 5]]
[[1 7]
 [9 2]]


In [22]:
c = a+b
c

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [24]:
x = np.random.randint(0,10,(3,3))
y = np.random.randint(0,10,3)
print(x)
print(y)

[[2 4 5]
 [5 5 7]
 [9 4 5]]
[6 5 6]


In [25]:
ans = x-y
ans

array([[-4, -1, -1],
       [-1,  0,  1],
       [ 3, -1, -1]])

In [26]:
a

array([[6, 1, 5],
       [2, 3, 5]])

In [28]:
tra = np.transpose(a)
tra

array([[6, 2],
       [1, 3],
       [5, 5]])

### Example

In [1]:
import numpy as np
import csv

with open('Datasets/year2017.csv') as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace = True)
    for row in data:
        print(row)

OrderedDict([('Year', '2017'), ('Month', '1'), ('Day', '2'), ('Country', 'Afghanistan'), ('Region', 'South Asia'), ('city', 'Takhta Pul'), ('latitude', '31.320556'), ('longitude', '65.961111'), ('AttackType', 'Hostage Taking (Kidnapping)'), ('Killed', '0.0'), ('Wounded', '0.0'), ('Target', 'Construction Workers'), ('Group', 'Taliban'), ('Target_type', 'Business'), ('Weapon_type', 'Firearms'), ('casualities', '0.0')])
OrderedDict([('Year', '2017'), ('Month', '1'), ('Day', '3'), ('Country', 'Sudan'), ('Region', 'Sub-Saharan Africa'), ('city', 'Fantaga'), ('latitude', '12.921007000000001'), ('longitude', '24.318324'), ('AttackType', 'Armed Assault'), ('Killed', '2.0'), ('Wounded', '0.0'), ('Target', 'Civilians: Haroun Yousif, Hamid Ibrahim'), ('Group', 'Unknown'), ('Target_type', 'Private Citizens & Property'), ('Weapon_type', 'Firearms'), ('casualities', '2.0')])
OrderedDict([('Year', '2017'), ('Month', '1'), ('Day', '1'), ('Country', 'Democratic Republic of the Congo'), ('Region', 'Sub-

OrderedDict([('Year', '2017'), ('Month', '3'), ('Day', '19'), ('Country', 'Iraq'), ('Region', 'Middle East & North Africa'), ('city', 'Mosul'), ('latitude', '36.354145'), ('longitude', '43.143570000000004'), ('AttackType', 'Bombing/Explosion'), ('Killed', '9.0'), ('Wounded', '0.0'), ('Target', 'Neighborhood'), ('Group', 'Islamic State of Iraq and the Levant (ISIL)'), ('Target_type', 'Private Citizens & Property'), ('Weapon_type', 'Explosives'), ('casualities', '9.0')])
OrderedDict([('Year', '2017'), ('Month', '3'), ('Day', '19'), ('Country', 'Iraq'), ('Region', 'Middle East & North Africa'), ('city', 'Mosul'), ('latitude', '36.354145'), ('longitude', '43.143570000000004'), ('AttackType', 'Bombing/Explosion'), ('Killed', '8.0'), ('Wounded', '0.0'), ('Target', 'Neighborhood'), ('Group', 'Islamic State of Iraq and the Levant (ISIL)'), ('Target_type', 'Private Citizens & Property'), ('Weapon_type', 'Explosives'), ('casualities', '8.0')])
OrderedDict([('Year', '2017'), ('Month', '3'), ('Day

OrderedDict([('Year', '2017'), ('Month', '5'), ('Day', '22'), ('Country', 'Iraq'), ('Region', 'Middle East & North Africa'), ('city', 'Mosul'), ('latitude', '36.354145'), ('longitude', '43.143570000000004'), ('AttackType', 'Bombing/Explosion'), ('Killed', '1.0'), ('Wounded', '0.0'), ('Target', 'Neighborhood'), ('Group', 'Islamic State of Iraq and the Levant (ISIL)'), ('Target_type', 'Private Citizens & Property'), ('Weapon_type', 'Explosives'), ('casualities', '1.0')])
OrderedDict([('Year', '2017'), ('Month', '5'), ('Day', '22'), ('Country', 'Iraq'), ('Region', 'Middle East & North Africa'), ('city', 'Mosul'), ('latitude', '36.354145'), ('longitude', '43.143570000000004'), ('AttackType', 'Bombing/Explosion'), ('Killed', '1.0'), ('Wounded', '0.0'), ('Target', 'Civilian'), ('Group', 'Islamic State of Iraq and the Levant (ISIL)'), ('Target_type', 'Private Citizens & Property'), ('Weapon_type', 'Explosives'), ('casualities', '1.0')])
OrderedDict([('Year', '2017'), ('Month', '5'), ('Day', '

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [4]:
with open('Datasets/year2017.csv') as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace = True)
    killed = []
    wounded = []
    country = []
    
    for row in data:
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        country.append(row['Country'])
        
    np_killed = np.array(killed)
    np_wounded = np.array(wounded)
    
    np_killed[np_killed == ""] = '0.0'
    np_wounded[np_wounded == ""] = '0.0'
    
    np_killed = np.array(np_killed,dtype = float)
    np_wounded = np.array(np_wounded,dtype = float)
    
    # Sum of killed and wounded for each row
    killed_wounded = np_killed+np_wounded
    
    # Print only for india
    np_country = np.array(country)
    bool_arr = np_country == 'India'
    ans = killed_wounded[bool_arr]
    print(np.sum(ans))

1167.0


#### Problem

Terrorism Day

Send Feedback

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

Problem Statement :
Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)
Print count of NumberOFAttack as integer value.

Output Format :
count


In [3]:
# Solution 1
import csv
import numpy as np
with open('Datasets/terrorismData.csv', errors= 'ignore') as file_obj:
    data = csv.DictReader(file_obj,skipinitialspace = True)
    
    attack = []
    for row in data :
        attack.append(row['Day'])
        
    attack_np = np.array(attack , dtype = float)
    
    array = np.logical_and(attack_np >= 10 , attack_np <= 20)
    ans  = attack_np[array]
    print(int(len(ans)))

66330


In [4]:
# Solution 2
import csv
import numpy as np
with open('Datasets/terrorismData.csv', errors= 'ignore') as file_obj:
    data = csv.DictReader(file_obj,skipinitialspace = True)
    
    attack = []
    for row in data :
        attack.append(row['Day'])
        
    attack_np = np.array(attack)
    attack_np = np.array(attack_np , dtype = float)
    ans  = attack_np[(attack_np >= 10) & (attack_np<=20)]
    print(ans.shape[0])

66330


#### Problem

Terrorism Date

Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

Problem Statement :
Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).
Note Ignore the case where day is 0

Print count of NumberOFAttack as integer value.

Output Format :
count

In [5]:
# Solution 1
import csv
import numpy as np
with open('Datasets/terrorismData.csv', errors= 'ignore') as file_obj:
    data = csv.DictReader(file_obj,skipinitialspace = True)
    
    attack = []
    
    for row in data :
        if row['Year']=='2010' and row['Month']== '1':
            attack.append(row['Day'])
        
    attack_np = np.array(attack , dtype = float)
    day = attack_np[(attack_np >= 1) & (attack_np<= 31)]
    
    print(len(day))

271


In [6]:
# Solution 2
import numpy as np
import csv
path="Datasets/terrorismData.csv"
date=[]
with open(path,'r',encoding='ISO-8859-1') as data:
    reader=csv.DictReader(data)

    for row in reader :
        date.append([row['Day'],row['Month'],row['Year']])
npdate=np.array(date,dtype=int)
npdate=npdate[npdate[:,2]==2010]
npdate=npdate[npdate[:,1]==1]
npdate=npdate[npdate[:,0]>=1]
print(npdate.shape[0])

271


#### Problem

Terror Casualty Attack

Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

Problem Statement :
As we knew the Kargil ( in Jammu and Kashmir) War that took place between May 1999 and July 1999 (3 Months) ,so there was a huge conflict in Kashmir Valley during this period.
In this dataset, there is no information regarding the war between the two countries to find out the casualty during the war.
So find out the attack in this period in which maximum casualties happened.
Print the count of casualties (as integer), city in which that attack happened and name of attack group.

Note : Casualty = Killed + Wounded.Fill the empty value in killed or wounded feature to 0.

Output Format :
Casualty City TerroristGroup

In [23]:
import csv
import numpy as np
with open("Datasets/terrorismData.csv",'r',encoding='ISO-8859-1') as file_obj:
    data = csv.DictReader(file_obj,skipinitialspace = True)
    
    details = []
    for row in data:
        details.append([row['Month'],row['Year'],row['City'],row['Group'],row['Wounded'],row['Killed'],row['State']])
        
    details_np = np.array(details)
    details_np = details_np[details_np[:,1]=='1999']
    details_np = details_np[(details_np[:,0]=='5') | (details_np[:,0]=='6') | (details_np[:,0]=='7')]
    details_np = details_np[details_np[:,6]=='Jammu and Kashmir']
        
    killed_np = details_np[:,5]
    killed_np[killed_np ==""] = '0'
    wounded_np = details_np[:,4]
    wounded_np[wounded_np ==''] = '0'
    killed_np = np.array(killed_np, dtype= float)
    wounded_np = np.array(wounded_np, dtype= float)
    casualty_np = killed_np + wounded_np
    casualty_np = np.array(casualty_np,dtype = int)
    
    index = casualty_np.argmax()
    
    print(casualty_np[index], details_np[index,2], details_np[index,3])

22 Kargil District Separatists


In [22]:
import csv
import numpy as np

with open("Datasets/terrorismData.csv",'r',encoding='ISO-8859-1') as file:
    data = csv.DictReader(file, skipinitialspace = True)
    
    killed = []
    wounded = []
    city = []
    group = []
    
    for row in data:
        
        if row['State'] == "Jammu and Kashmir" and row["Year"] == "1999" and (row['Month']=="5" or row['Month']=="6" or row["Month"]=="7"):
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
            city.append(row['City'])
            group.append(row['Group'])
            
    killed = np.array(killed)
    killed[killed == ""] = "0.0"
    killed = np.array(killed, dtype=float)
    
    wounded = np.array(wounded)
    wounded[wounded == ""] = "0.0"
    wounded = np.array(wounded, dtype=float)
    
    casualties = killed + wounded
    index = casualties.argmax()
    
    print(int(casualties[index]), city[index], group[index] )

22 Kargil District Separatists


#### Problem

Terror Casualty Red

Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

Problem Statement :
Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.

Note: Casualty=Killed +Wounded

Print count of Casualty as integer value.
Output Format :
Count

In [19]:
## Solution 1
import csv
import numpy as np
with open("Datasets/terrorismData.csv",'r',encoding='ISO-8859-1') as file_obj:
    data = csv.DictReader(file_obj,skipinitialspace = True)
    
    details = []
    for row in data:
        details.append([row['State'],row['Wounded'],row['Killed']])
        
    
    details_np = np.array(details)
    details_np = details_np[(details_np[:,0]=='Jharkhand') | (details_np[:,0]=='Odisha') | (details_np[:,0]=='Andhra Pradesh') | (details_np[:,0]=='Chhattisgarh')]
        
    killed_np = details_np[:,2]
    killed_np[killed_np ==""] = '0'
    wounded_np = details_np[:,1]
    wounded_np[wounded_np ==''] = '0'
    killed_np = np.array(killed_np, dtype= float)
    wounded_np = np.array(wounded_np, dtype= float)
    casualty_np = killed_np + wounded_np
    casualty_np = np.array(casualty_np,dtype = int)
    
    print(casualty_np.sum())
       

5628


In [21]:
# Solution 2
import csv
import numpy as np

with open("Datasets/terrorismData.csv", "r",encoding='ISO-8859-1') as file:
    data = csv.DictReader(file, skipinitialspace = True)
    
    casualties = []
    red = {'Jharkhand', 'Odisha', 'Andhra Pradesh', 'Chhattisgarh'}
    
    for row in data:
        
        if row['State'] in red:
            casualties.append([row['Killed'], row['Wounded']])
            
    casualties = np.array(casualties)
    casualties[casualties == ""] = "0.0"
    casualties = np.array(casualties, dtype=float)
    
    ans = casualties.sum()
    print(int(ans))

5628


#### Problem

Terror City Casualty

Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

Problem Statement :
Find top 5 Indian Cities which has most number of casualties ?
Print top 5 cities along with total casualties in that city. Print count of Casualty as integer value.

Note: Ignoring the City which is Unknown.
Casualty = Killed + Wounded.

Output Format :
city_1 casualty_1
city_2 casualty_2
city_3 casualty_3
city_4 casualty_4
city_5 casualty_5


In [26]:
import csv
import numpy as np

city = []
casualty = []

with open("Datasets/terrorismData.csv", "r",encoding='ISO-8859-1') as file:
    data = csv.DictReader(file, skipinitialspace = True)
    for row in data:
        if row['Country']=='India':
            if row['City']!= 'Unknown':
                city.append(row['City'])
                casualty.append([row['Killed'],row['Wounded']])
casualty_np = np.array(casualty)
city_np = np.array(city)

casualty_np[casualty_np=='']=0
casualty_np=np.array(casualty_np,dtype=float)

#Sum alog row (axis = 1)
casualty_np=np.sum(casualty_np,axis=1)
def cityCasualty(cityarr,casualtyarr):
    arr = []
    unique = np.unique(cityarr)
    for i in unique:
        index, = np.where(cityarr==i)
        sumCasualty = casualtyarr[index].sum()
        arr.append([sumCasualty,i])
    arr.sort(reverse=True)
    return arr
arr = cityCasualty(city_np,casualty_np)
for i in range(5):
    print(arr[i][1],int(arr[i][0]))

Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


#### Problem

Terrorism FrequentDay

Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period

Problem Statement :
Find the most frequent day of attack in a terrorismDataset ?

Note: Here np.unique can be used.

Print count of frequent day and number of attack as Integer value.

Output Format :
Day NumberOFAttack

In [8]:
## Open and read data file as specified in the question
## Print the required output in given format
import csv
import numpy as np

with open("Datasets/terrorismData.csv", "r",encoding='ISO-8859-1') as file:
    data = csv.DictReader(file, skipinitialspace = True)
    day = []
    for row in data:
        day.append(row['Day'])
    day_np = np.array(day,dtype = int)
    
    unique_arr = np.unique(day_np)
    
    arr = []
    for i in unique_arr:
        temp = day_np[day_np== i]
        NoAttack = len(temp)
        arr.append([i,NoAttack])
        
    arr_np = np.array(arr)
    count = arr_np[:,1]
    ind = np.argmax(count)
    print(arr_np[ind][0],arr_np[ind][1])

15 6500


In [2]:
import csv
import numpy as np

with open("Datasets/terrorismData.csv", "r",encoding='ISO-8859-1') as file:
    data = csv.DictReader(file, skipinitialspace = True)
    day = []
    for row in data:
        day.append(row['Day'])
    day_np = np.array(day,dtype = 'int')
    day, count=np.unique(day_np, return_counts=True)
    print(day[np.argmax(count)], count[np.argmax(count)])

15 6500
